// <auto-generated />
namespace X_StateOnline.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Order_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_init));
        
        string IMigrationMetadata.Id
        {
            get { return "202210120618236_Order_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
